### ISSUE TITLE
Windows compilation

### ISSUE THREAD

**Issue by cdemez** [rigtorp/SPSCQueue#1]
Hi Erik,

It does not compile under MS windows, you use some GNU specific stuffs !

Thx

**Comment by rigtorp** [comment]
Yeah, the benchmarks do. The implementation itself should be cross platform.

**Comment by cdemez** [comment]
Thanks,

But I talk about the implementation, you use stuffs like ssize_t that only exists on linux.
Also, there are other compilation error (VS 2017)

Thx
