### ISSUE TITLE
Provide a way to let consumer know push failed

### ISSUE THREAD

**Issue by azuresigma** [rigtorp/SPSCQueue#17]
The use case is, if consumer is slow to keep up with incoming events in the queue, consumer can know about it and decide to quit, instead of making bad decisions based on stale information. 

One easy way I can think of, is to have a failedPushCount that can be checked by user. User can decide to continue if failedPushCount(number of dropped messages) is small and stop if the number exceeds a pre-defined threshold. 

It is up to the main implementation. The most important feature I am looking for is to notify consumer if push fails. 

Thanks.

**Comment by rigtorp** [comment]
That's easy to do by wrapping or subclassing SPSCQueue inside another class.
