### ISSUE TITLE
optimize front() for bust of data

### ISSUE THREAD

**Issue by azuresigma** [rigtorp/SPSCQueue#18]
currently, front() always do head_.load(std::memory_order_acquire. I think it can load(std::memory_order_relaxed) first, then try to load(std::memory_order_acquire). This will help when producer has a lot of data coming in at the same time. 

Facebook folly queue has a pull request for this. https://github.com/facebook/folly/pull/1133. Not sure why it was not accepted into master.

**Comment by rigtorp** [comment]
Yes this is an interesting optimization.
