### ISSUE TITLE
The alignment of Slot?

### ISSUE THREAD

**Issue by constroy** [rigtorp/SPSCQueue#21]
I think the alignment of `Slot` can avoid false sharing between items, like how we do in [MPMCQueue](https://github.com/rigtorp/MPMCQueue/blob/master/include/rigtorp/MPMCQueue.h#L108).
Should we also use an alignment of `Slot` in an SPSCQueue?

**Comment by rigtorp** [comment]
There is a trade off there, it leads to higher memory use. For a almost full SPSCQueue there is no advantage to having the cache line alignment. For a almost empty queue it prevents false sharing. In the MPSCQueue there would always be false sharing due to multiple producers and consumers.

**Comment by constroy** [comment]
I've got it. Thanks a lot!
