### ISSUE TITLE
Error with __cpp_lib_hardware_interference_size on MacOS llvm-g++ 12.x

### ISSUE THREAD

**Issue by hile** [rigtorp/SPSCQueue#22]
The check for __cpp_lib_hardware_interference_size in include/rigtorp/SPSCQueue.h seems to incorrectly indicate this feature is available in MacOS llvm-g++ but it's not really implemented.

Not sure how this should be checked correctly, but for example following post suggests instead

#if __cpp_lib_hardware_interference_size >= 201603

This was seen on MacOS 10.15 with xcode CLI tools 12.1 and llvm-g++ version clang-1200.0.32.21

**Comment by Be-ing** [comment]
Seems like a bug in libc++, not SPSCQueue: https://bugs.llvm.org/show_bug.cgi?id=41423

**Comment by rigtorp** [comment]
Closing this since the bug is in LLVM. You can easily remove this code for your local use.

**Comment by Be-ing** [comment]
We ended up hacking around it by checking whether it's built on macOS: https://github.com/mixxxdj/mixxx/pull/3318
