### ISSUE TITLE
Minimum Capacity 

### ISSUE THREAD

**Issue by bftjoe** [rigtorp/SPSCQueue#25]
Is the minimum capacity 2 or 3? The example uses 2 but then it says "Capacity need to be greater than 2."

**Comment by mgood7123** [comment]
> Is the minimum capacity 2 or 3? The example uses 2 but then it says "Capacity need to be greater than 2."

try it and see

**Comment by bftjoe** [comment]
Regardless, either the documentation or the example is wrong and should be corrected.

**Comment by rigtorp** [comment]
The documentation was wrong, It's been updated. Thanks for noticing.
