### ISSUE TITLE
COMPILE ERROR Mac OS - hardware_destructive_interference_size is not found

### ISSUE THREAD

**Issue by mgood7123** [rigtorp/SPSCQueue#26]
https://jira.mongodb.org/browse/SERVER-44270 only issue i can find that is related to this

`__cpp_lib_hardware_interference_size` is defined even though `std::hardware_destructive_interference_size` is not found

when using

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

this does not occur when using

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

or

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

**Comment by rigtorp** [comment]
That's a bug in LLVM. Just comment out that code until your compiler is fixed
