### ISSUE TITLE
 replace (std::memory_order_release ,std::memory_order_acquire) with (std::memory_order_relax)?

### ISSUE THREAD

**Issue by lglgdouble** [rigtorp/SPSCQueue#34]
readIdx_.store(nextReadIdx, std::memory_order_release);

      while ( nextWriteIdx == readIdxCache_ ) {
        readIdxCache_ = readIdx_.load(std::memory_order_acquire);
      }

 replace (std::memory_order_release ,std::memory_order_acquire) with (std::memory_order_relax)?

**Comment by rigtorp** [comment]
No, that would allow incorrect memory inter-leavings. What makes you think that you can always use memory order relaxed?
