### ISSUE TITLE
Memory buffer

### ISSUE THREAD

**Issue by alphanso** [rigtorp/SPSCQueue#39]
How to use spsc queue as memory queue. I want to use this for dumping binary data which I will read from a different thread and write it to files.

**Comment by rigtorp** [comment]
Yes, SPSCQueue can be used for that purpose. What is your specific issue
with SPSCQueue?

**Comment by alphanso** [comment]
I wanted to use memcpy or something that efficient to write binary data. Queue APIs demand object and I couldn't understand how to use that. I believe I will need SPSCQueue<std::byte> for that. I couldn't figure out how to read and write to Queue using your apis

Example to use it as a binary data buffer will be very useful to me. Also, I am really thankful for outsourcing this implementation.

**Comment by rigtorp** [comment]
You could try SPSCQueue<char> ?

I think you might be interested in using a bipbuffer instead.
